# ================================
# Pipeline Configuration
# ================================

artifacts_root: artifacts

# ================================
# Data Ingestion Configuration
# ================================

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data_path: data/raw/Telco-Customer-Churn.csv
  local_data_file: artifacts/data_ingestion/raw.csv

# ================================
# Data Validation Configuration
# ================================

# Inside config/config.yaml
data_validation:
  root_dir: artifacts/data_validation
  schema_raw: schema.yaml              
  schema_processed: schema_processed.yaml
  validation_report: artifacts/data_validation/report.json

# ================================
# Data Cleaning Configuration
# ================================

data_cleaning:
  root_dir: artifacts/data_cleaning
  cleaned_data_path: artifacts/data_cleaning/cleaned.csv

# ================================
# Feature Engineering Configuration
# ================================

feature_engineering:
  root_dir: artifacts/feature_engineering
  featured_data_path: artifacts/feature_engineering/featured.csv

# ================================
# Data Transformation Configuration
# ================================

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_train: artifacts/data_transformation/X_train.npy
  transformed_test: artifacts/data_transformation/X_test.npy
  y_train: artifacts/data_transformation/y_train.npy
  y_test: artifacts/data_transformation/y_test.npy
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl

# ================================
# Model Training Configuration
# ================================

model_trainer:
  root_dir: artifacts/model_trainer
  model_path: artifacts/model_trainer/model.pkl

# ================================
# Model Evaluation Configuration
# ================================

model_evaluation:
  root_dir: artifacts/model_evaluation
  metrics_path: artifacts/model_evaluation/metrics.json

# ================================
# Model Deployment / Serving
# ================================

model_serving:
  model_path: artifacts/model_trainer/model.pkl
  preprocessor_path: artifacts/data_transformation/preprocessor.pkl
